name: zero_hunger_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4
  firebase_storage: 11.7.7
  cupertino_icons: ^1.0.6
  google_sign_in:
  provider: ^6.1.2
  google_maps_flutter: ^2.6.1
  flutter_local_notifications: ^17.1.2
  geolocator:
  location:
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  image_picker: ^0.8.4+8

flutter:
  uses-material-design: true
  assets:
    - assets/images/campaign1.png
    - assets/images/event2.jpg
    - assets/images/news1.png
    - assets/images/update2.png
    - assets/images/event_reminder.png
    - assets/images/volunteer_meeting.png
    - assets/images/meal_prep.png
    - assets/images/donation_organizer.png
    - assets/images/background.png
    - assets/images/baby_supply_main.jpg
    - assets/images/baby1.jpg
    - assets/images/bedding_main.jpg
    - assets/images/building_main.jpg
    - assets/images/clothes_main.jpg
    - assets/images/elec_main.jpg
    - assets/images/elec1.jpg
    - assets/images/food_main.jpg
    - assets/images/footwear_main.jpg
    - assets/images/footwear1.jpg
    - assets/images/furniture_main.jpg
    - assets/images/kitchen_main.jpg
    - assets/images/med1.jpg
    - assets/images/medical_main.jpg
    - assets/images/mobility_main.jpg
    - assets/images/other_main.jpg
    - assets/images/personal_hygiene_main.jpg

    - assets/images/bed1.jpg
    - assets/images/bed2.jpg
    - assets/images/bed3.jpg
    - assets/images/bed4.jpg
    - assets/images/build1.jpg
    - assets/images/build2.jpg
    - assets/images/build3.jpg
    - assets/images/sup1.jpg
    - assets/images/cloth1.jpg
    - assets/images/cloth2.jpg
    - assets/images/cloth3.jpg
    - assets/images/cloth4.jpg
    - assets/images/elec2.jpg
    - assets/images/elec3.jpg
    - assets/images/elec4.jpg
    - assets/images/food1.jpg
    - assets/images/food2.jpg
    - assets/images/food3.jpg
    - assets/images/food4.jpg
    - assets/images/foot1.jpg
    - assets/images/foot2.jpg
    - assets/images/foot3.jpg
    - assets/images/foot4.jpg
    - assets/images/fun1.jpg
    - assets/images/fun2.jpg
    - assets/images/fun3.jpg
    - assets/images/fun4.jpg
    - assets/images/kitchen1.jpg
    - assets/images/kitchen2.jpg
    - assets/images/kitchen3.jpg
    - assets/images/kitchen4.jpg
    - assets/images/med1.jpg
    - assets/images/med2.jpg
    - assets/images/med3.jpg
    - assets/images/med4.jpg
    - assets/images/mob1.jpg
    - assets/images/mob2.jpg
    - assets/images/mob3.jpg
    - assets/images/mob4.jpg
    - assets/images/other1.jpg
    - assets/images/other2.jpg
    - assets/images/other3.jpg
    - assets/images/other4.jpg
    - assets/images/pro1.jpg
    - assets/images/pro2.jpg
    - assets/images/pro3.jpg
    - assets/images/pro4.jpg
    - assets/images/sup2.jpg
    - assets/images/sup3.jpg
    - assets/images/sup4.jpg
    - assets/images/elec5.jpg
