// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1NXiR1wuo2BFxtTolgdCtWVcwPeJjL3E',
    appId: '1:164692002382:web:069eb2b6becfc6a74e651f',
    messagingSenderId: '164692002382',
    projectId: 'food-rescue-app-e9f4f',
    authDomain: 'food-rescue-app-e9f4f.firebaseapp.com',
    storageBucket: 'food-rescue-app-e9f4f.appspot.com',
    measurementId: 'G-S05KB74Q3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd-nAgIOEYvgTseaFlU1ebPxeeXi__bYQ',
    appId: '1:164692002382:android:019e07a2a8132dc54e651f',
    messagingSenderId: '164692002382',
    projectId: 'food-rescue-app-e9f4f',
    storageBucket: 'food-rescue-app-e9f4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZRcSmHm1321PrJDxNGP1aiklhJeSZbsY',
    appId: '1:164692002382:ios:509ac506466e012b4e651f',
    messagingSenderId: '164692002382',
    projectId: 'food-rescue-app-e9f4f',
    storageBucket: 'food-rescue-app-e9f4f.appspot.com',
    iosBundleId: 'com.example.zeroHungerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZRcSmHm1321PrJDxNGP1aiklhJeSZbsY',
    appId: '1:164692002382:ios:509ac506466e012b4e651f',
    messagingSenderId: '164692002382',
    projectId: 'food-rescue-app-e9f4f',
    storageBucket: 'food-rescue-app-e9f4f.appspot.com',
    iosBundleId: 'com.example.zeroHungerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1NXiR1wuo2BFxtTolgdCtWVcwPeJjL3E',
    appId: '1:164692002382:web:4080f5fa5aeb473a4e651f',
    messagingSenderId: '164692002382',
    projectId: 'food-rescue-app-e9f4f',
    authDomain: 'food-rescue-app-e9f4f.firebaseapp.com',
    storageBucket: 'food-rescue-app-e9f4f.appspot.com',
    measurementId: 'G-T2VVX5F22K',
  );
}
